### PR TITLE
Emit a console.warn when doing any overrides on a tab. Fixes #47

### LINKED ISSUE #47: Emit a console.warn when doing an override
In https://bugzilla.mozilla.org/show_bug.cgi?id=1531509 it was reported that having a console message could help developer understand what's going on.

A console warning could be a good start (the message can be styled to be bigger than other messages if we want that `console.warn("%cThis website has compatibility issues […]", "font-size: 48px;")`).

### PR DESCRIPTION
**Pull request by wisniewskit**
Note that no attempt is made in this patch to do any l10n on the related messages, because there is no FTL interface on content scripts for system addons yet (and it can rely on strings which already aren't being localized, like the ones for the PDK fix, which is hard-coded to use the string "Sites using PDK 5" right now about:compat).

Unless I've missed a memo or two, we currently would have to do things how the [webcompat reporter is doing](https://searchfox.org/mozilla-central/source/browser/extensions/report-site-issue/experimentalAPIs/l10n.js) (which I think other addons are doing as well). But I'm not sure if that's what we want to do. We should check with the l10n team to make a decision here.

### CODE REVIEW

**Comment by wisniewskit** [comment]
Yes, I'll squash the commits/etc after I've had a chance to consider l10n, just in case we should adopt the same solution other system addons are using for now (which wouldn't be too tricky to add to this patch).

**Comment by miketaylr** [comment]
What's the status here @wisniewskit?

**Comment by miketaylr** [comment]
@denschub is this something we still want, or should we close this?

**Comment by denschub** [comment]
@miketaylr I'd say this is a solid "nice to have", still. Probably ignoring l10n and just having it English-only is better than not emitting a warning in some cases.

**Comment by miketaylr** [comment]
@denschub thanks, can you take this over then?

**Comment by denschub** [comment]
Self-assigning this, I'll do the rebase. :)

**Comment by denschub** [comment]
Rebased in #185.

**Pull request closed without merging**
